export const SET_IMAGE_LOADED = "SET_IMAGE_LOADED";
export const SET_CANVAS_FUNCTIONS = "SET_CANVAS_FUNCTIONS";
export const SET_CANVAS_ELEMENTS = "SET_CANVAS_ELEMENTS";
export const SET_SELECTION_INFO = "SET_SELECTION_INFO";
export const SHOW_DISABLE_SELECTION_TOOLTIP = "SHOW_DISABLE_SELECTION_TOOLTIP";